// Built-in recipe library. Ingredient quantities are PER ADULT SERVING, in the catalog item's unit.
// Prices are rough US grocery averages and only drive estimates.

export const AISLES = ['Produce', 'Meat & seafood', 'Dairy, eggs & tofu', 'Bakery & grains', 'Canned & dry goods', 'Frozen', 'Pantry & spices'];
const [PR, MS, DE, BG, CD, FZ, PS] = AISLES;

// key: [name, unit, USD per unit, aisle, flags]
// flags: M meat · F fish · C shellfish · D dairy · E egg · G gluten · N nuts · H honey
export const CATALOG = {
  chix: ['Chicken breast', 'lb', 4.5, MS, 'M'],
  thigh: ['Boneless chicken thighs', 'lb', 3.8, MS, 'M'],
  turkey: ['Ground turkey (93% lean)', 'lb', 5, MS, 'M'],
  beef: ['Lean ground beef (93%)', 'lb', 6.5, MS, 'M'],
  deli: ['Sliced turkey breast', 'oz', 0.6, MS, 'M'],
  salmon: ['Salmon fillet', 'lb', 10, MS, 'F'],
  cod: ['Cod fillet', 'lb', 8.5, MS, 'F'],
  shrimp: ['Peeled shrimp', 'lb', 9, MS, 'C'],
  eggs: ['Eggs', 'each', 0.3, DE, 'E'],
  yogurt: ['Plain Greek yogurt', 'oz', 0.16, DE, 'D'],
  milk: ['Milk', 'cup', 0.25, DE, 'D'],
  soymilk: ['Unsweetened soy milk', 'cup', 0.3, DE, ''],
  cottage: ['Cottage cheese', 'oz', 0.18, DE, 'D'],
  cheddar: ['Cheddar cheese', 'oz', 0.35, DE, 'D'],
  feta: ['Feta cheese', 'oz', 0.55, DE, 'D'],
  parm: ['Parmesan', 'oz', 0.75, DE, 'D'],
  mozz: ['Mozzarella', 'oz', 0.35, DE, 'D'],
  tofu: ['Firm tofu', 'oz', 0.18, DE, ''],
  hummus: ['Hummus', 'oz', 0.35, DE, ''],
  bread: ['Whole-grain bread', 'slice', 0.25, BG, 'G'],
  wwtort: ['Whole-wheat tortillas', 'each', 0.4, BG, 'G'],
  corntort: ['Corn tortillas', 'each', 0.1, BG, ''],
  pita: ['Whole-wheat pita', 'each', 0.5, BG, 'G'],
  oats: ['Rolled oats', 'lb', 1.6, BG, ''],
  rice: ['Brown rice', 'lb', 1.8, BG, ''],
  quinoa: ['Quinoa', 'lb', 5, BG, ''],
  pasta: ['Whole-wheat pasta', 'lb', 1.9, BG, 'G'],
  noodles: ['Rice noodles', 'oz', 0.22, BG, ''],
  lentils: ['Dry lentils', 'lb', 1.8, CD, ''],
  blackb: ['Black beans (15 oz)', 'can', 1.1, CD, ''],
  chick: ['Chickpeas (15 oz)', 'can', 1.1, CD, ''],
  kidney: ['Kidney beans (15 oz)', 'can', 1.1, CD, ''],
  tomcan: ['Diced tomatoes (15 oz)', 'can', 1.4, CD, ''],
  coco: ['Light coconut milk', 'can', 2.2, CD, ''],
  tuna: ['Canned tuna (5 oz)', 'can', 1.5, CD, 'F'],
  vbroth: ['Low-sodium vegetable broth', 'cup', 0.5, CD, ''],
  cbroth: ['Low-sodium chicken broth', 'cup', 0.5, CD, 'M'],
  salsa: ['Salsa', 'cup', 1.6, CD, ''],
  pb: ['Peanut butter', 'tbsp', 0.1, PS, 'N'],
  almonds: ['Almonds', 'oz', 0.5, PS, 'N'],
  chia: ['Chia seeds', 'tbsp', 0.2, PS, ''],
  oil: ['Olive oil', 'tbsp', 0.15, PS, ''],
  sesoil: ['Sesame oil', 'tbsp', 0.2, PS, ''],
  soy: ['Low-sodium soy sauce', 'tbsp', 0.08, PS, 'G'],
  honey: ['Honey', 'tbsp', 0.2, PS, 'H'],
  maple: ['Maple syrup', 'tbsp', 0.3, PS, ''],
  curry: ['Curry paste', 'tbsp', 0.3, PS, ''],
  spice: ['Chili & cumin spice blend', 'tsp', 0.1, PS, ''],
  cinn: ['Cinnamon', 'tsp', 0.05, PS, ''],
  ginger: ['Ground ginger', 'tsp', 0.1, PS, ''],
  swpot: ['Sweet potatoes', 'lb', 1.3, PR, ''],
  potato: ['Potatoes', 'lb', 1, PR, ''],
  broc: ['Broccoli', 'lb', 2.2, PR, ''],
  spinach: ['Baby spinach', 'oz', 0.4, PR, ''],
  greens: ['Mixed salad greens', 'oz', 0.45, PR, ''],
  romaine: ['Romaine lettuce', 'head', 2, PR, ''],
  pepper: ['Bell peppers', 'each', 1.2, PR, ''],
  onion: ['Onions', 'each', 0.8, PR, ''],
  garlic: ['Garlic', 'clove', 0.1, PR, ''],
  carrot: ['Carrots', 'lb', 1.1, PR, ''],
  zucc: ['Zucchini', 'lb', 1.8, PR, ''],
  tomato: ['Tomatoes', 'each', 0.8, PR, ''],
  cuke: ['Cucumbers', 'each', 0.9, PR, ''],
  avo: ['Avocados', 'each', 1.25, PR, ''],
  banana: ['Bananas', 'each', 0.25, PR, ''],
  lemon: ['Lemons', 'each', 0.6, PR, ''],
  lime: ['Limes', 'each', 0.4, PR, ''],
  cabbage: ['Cabbage', 'lb', 0.9, PR, ''],
  gbeans: ['Green beans', 'lb', 2.5, PR, ''],
  cauli: ['Cauliflower', 'head', 3, PR, ''],
  scal: ['Green onions', 'bunch', 1, PR, ''],
  berries: ['Frozen mixed berries', 'oz', 0.3, FZ, ''],
  peas: ['Frozen peas', 'oz', 0.12, FZ, ''],
  mixveg: ['Frozen mixed vegetables', 'oz', 0.12, FZ, ''],
  caulirice: ['Frozen cauliflower rice', 'oz', 0.2, FZ, ''],
  edamame: ['Frozen shelled edamame', 'oz', 0.25, FZ, ''],
};

// (id, name, meal, kcal, protein g, carbs g, minutes, 'key:qty …', 'step|step')
const R = (id, name, meal, kcal, protein, carbs, minutes, ing, steps) => {
  const ingredients = ing.split(' ').map(p => { const [key, qty] = p.split(':'); return { key, qty: +qty }; });
  const flags = [...new Set(ingredients.flatMap(i => [...CATALOG[i.key][4]]))].join('');
  const cost = ingredients.reduce((sum, i) => sum + i.qty * CATALOG[i.key][2], 0);
  return { id, name, meal, kcal, protein, carbs, minutes, ingredients, flags, cost, steps: steps.split('|') };
};

export const RECIPES = [
  R('b-oats', 'Overnight oats with berries', 'breakfast', 380, 18, 55, 5, 'oats:.09 milk:.5 yogurt:2 berries:2 chia:1 maple:.5', 'Stir oats, milk, yogurt and chia together in a jar.|Top with berries and a drizzle of maple syrup.|Refrigerate overnight and eat cold.'),
  R('b-scramble', 'Veggie egg scramble with toast', 'breakfast', 330, 18, 20, 10, 'eggs:2 spinach:1 pepper:.25 bread:1 oil:.5', 'Sauté diced pepper in oil for 3 minutes, then add spinach until wilted.|Add beaten eggs and stir gently until just set.|Serve with toast.'),
  R('b-parfait', 'Greek yogurt parfait', 'breakfast', 300, 20, 30, 5, 'yogurt:6 berries:2 almonds:.5 honey:.5', 'Layer yogurt and thawed berries in a bowl.|Top with chopped almonds and honey.'),
  R('b-pbtoast', 'Peanut butter banana toast', 'breakfast', 380, 13, 50, 5, 'bread:2 pb:1.5 banana:1 cinn:.25', 'Toast bread and spread with peanut butter.|Top with sliced banana and a pinch of cinnamon.'),
  R('b-muffins', 'Spinach & feta egg muffins', 'breakfast', 220, 15, 5, 25, 'eggs:2 spinach:1 feta:.5 pepper:.25 onion:.1', 'Heat oven to 350°F and grease a muffin tin.|Whisk eggs; fold in chopped spinach, pepper, onion and feta.|Pour into cups and bake 20 minutes. Keeps 4 days in the fridge.'),
  R('b-tofu', 'Tofu scramble tacos', 'breakfast', 320, 20, 25, 15, 'tofu:5 spinach:1 onion:.15 pepper:.25 spice:.5 oil:.5 corntort:2', 'Crumble tofu into a hot oiled pan with diced onion and pepper.|Season with spice blend, cook 5 minutes, then stir in spinach.|Serve in warm corn tortillas.'),
  R('b-pancakes', 'Banana oat pancakes', 'breakfast', 330, 12, 55, 15, 'oats:.09 banana:1 eggs:1 milk:.25 cinn:.25 berries:1', 'Blend oats, banana, egg, milk and cinnamon until smooth.|Cook ¼-cup scoops on a hot nonstick pan, 2 minutes per side.|Top with warmed berries.'),
  R('b-smoothie', 'Berry spinach smoothie', 'breakfast', 330, 18, 55, 5, 'berries:3 banana:1 spinach:1 yogurt:4 milk:.5 chia:1', 'Blend everything until smooth, adding milk to thin if needed.'),
  R('b-burrito', 'Egg & black bean breakfast burrito', 'breakfast', 420, 22, 40, 15, 'eggs:2 blackb:.15 wwtort:1 salsa:.1 cheddar:.5', 'Scramble eggs and warm the rinsed black beans.|Fill tortilla with eggs, beans, cheese and salsa; roll up.|Make extra and freeze wrapped in foil.'),
  R('b-cottage', 'Cottage cheese fruit bowl', 'breakfast', 250, 22, 20, 5, 'cottage:6 berries:2 chia:1', 'Top cottage cheese with thawed berries and chia seeds.'),
  R('b-avotoast', 'Avocado toast with egg', 'breakfast', 280, 11, 20, 10, 'bread:1 avo:.5 eggs:1 lemon:.1', 'Toast bread and mash avocado on top with a squeeze of lemon.|Top with a fried or boiled egg.'),
  R('b-proteinbowl', 'Greek yogurt protein bowl', 'breakfast', 380, 28, 30, 5, 'yogurt:8 berries:2 chia:1 almonds:.5', 'Spoon yogurt into a bowl.|Top with thawed berries, chia seeds and chopped almonds.'),
  R('b-turkeyeggs', 'Turkey & spinach egg scramble', 'breakfast', 360, 32, 15, 10, 'eggs:3 deli:2 spinach:1 bread:1 oil:.5', 'Warm chopped turkey and spinach in oil for 2 minutes.|Add beaten eggs and stir until just set.|Serve with toast.'),
  R('b-chia', 'Vanilla chia pudding', 'breakfast', 300, 12, 30, 5, 'chia:3 soymilk:1 berries:2 maple:.5', 'Whisk chia seeds into soy milk and maple syrup.|Rest 10 minutes, stir again and refrigerate overnight.|Top with berries.'),

  R('l-wrap', 'Turkey hummus wrap', 'lunch', 380, 28, 35, 5, 'wwtort:1 deli:3 hummus:1 spinach:.75 cuke:.25', 'Spread hummus on the tortilla.|Layer turkey, spinach and sliced cucumber; roll tightly and halve.'),
  R('l-chicksand', 'Smashed chickpea salad sandwich', 'lunch', 400, 16, 60, 10, 'chick:.4 lemon:.25 cuke:.25 hummus:.5 bread:2', 'Mash chickpeas with hummus, lemon juice, salt and pepper.|Stir in diced cucumber.|Spread between bread slices.'),
  R('l-quinoa', 'Quinoa black bean bowl', 'lunch', 480, 17, 70, 20, 'quinoa:.1 blackb:.3 mixveg:2 salsa:.15 avo:.25 lime:.25', 'Cook quinoa (1 part to 2 parts water, 15 minutes).|Warm beans and vegetables.|Top quinoa with beans, veg, salsa, avocado and lime.'),
  R('l-tuna', 'Tuna salad lettuce wraps', 'lunch', 230, 32, 7, 10, 'tuna:1 yogurt:1 romaine:.25 cuke:.25 lemon:.15', 'Mix drained tuna with yogurt, lemon juice and diced cucumber.|Spoon into romaine leaves.'),
  R('l-lentilsoup', 'Lentil vegetable soup', 'lunch', 330, 20, 52, 40, 'lentils:.15 carrot:.15 onion:.25 tomcan:.25 vbroth:1.5 spinach:1 spice:.5 garlic:1', 'Sauté diced onion, carrot and garlic for 5 minutes.|Add rinsed lentils, tomatoes, broth and spices; simmer 30 minutes.|Stir in spinach. Freezes well.'),
  R('l-greekchix', 'Greek chicken salad', 'lunch', 420, 40, 10, 20, 'chix:.3 romaine:.25 cuke:.5 tomato:.5 feta:.75 oil:1 lemon:.25', 'Season and pan-cook chicken 6 minutes per side; slice.|Chop romaine, cucumber and tomato.|Toss with olive oil and lemon; top with chicken and feta.'),
  R('l-hummusplate', 'Mediterranean hummus plate', 'lunch', 420, 14, 50, 10, 'pita:1 hummus:2 cuke:.5 tomato:.5 carrot:.1 feta:.5', 'Warm pita and cut into wedges.|Plate with hummus, sliced vegetables and crumbled feta.'),
  R('l-eggsalad', 'Egg salad lettuce cups', 'lunch', 220, 16, 5, 15, 'eggs:2 yogurt:1 romaine:.25 tomato:.25', 'Hard-boil eggs 10 minutes, cool and chop.|Mix with yogurt, salt and pepper.|Serve in romaine leaves with diced tomato.'),
  R('l-peanut', 'Peanut noodle salad', 'lunch', 470, 18, 65, 15, 'noodles:2 pb:1 soy:1 cabbage:.15 carrot:.1 edamame:2 lime:.25', 'Soak or boil rice noodles per the package; rinse cold.|Whisk peanut butter, soy sauce, lime and a splash of hot water.|Toss with shredded cabbage, carrot and thawed edamame.'),
  R('l-burritobowl', 'Chicken burrito bowl', 'lunch', 520, 40, 60, 25, 'chix:.25 rice:.1 blackb:.2 salsa:.15 romaine:.15 lime:.25 spice:.5', 'Cook rice.|Season chicken with spice blend and cook 6 minutes per side; slice.|Build bowls with rice, beans, lettuce, chicken, salsa and lime.'),
  R('l-minestrone', 'Minestrone soup', 'lunch', 340, 14, 58, 35, 'tomcan:.3 kidney:.25 pasta:.06 zucc:.15 carrot:.1 onion:.2 vbroth:1.5 garlic:1 spinach:.5', 'Sauté onion, carrot and garlic 5 minutes.|Add tomatoes, broth, beans and zucchini; simmer 15 minutes.|Add pasta, cook 10 minutes and stir in spinach.'),
  R('l-caprese', 'Caprese chickpea salad', 'lunch', 400, 19, 40, 10, 'chick:.4 tomato:1 mozz:1 cuke:.5 oil:.5 greens:1', 'Rinse chickpeas; chop tomato, cucumber and mozzarella.|Toss with greens, olive oil, salt and pepper.'),

  R('d-sheetpan', 'Sheet-pan chicken & sweet potatoes', 'dinner', 450, 40, 38, 40, 'chix:.33 swpot:.35 broc:.25 oil:1 spice:.5 garlic:1', 'Heat oven to 425°F.|Toss cubed sweet potato with half the oil; roast 15 minutes.|Add chicken pieces, broccoli, garlic, spices and remaining oil; roast 20 minutes more.'),
  R('d-chili', 'Turkey & bean chili', 'dinner', 400, 34, 35, 40, 'turkey:.25 kidney:.3 tomcan:.35 onion:.25 pepper:.3 spice:1 garlic:1', 'Brown turkey with diced onion, pepper and garlic.|Add tomatoes, beans and spices; simmer 25 minutes.|Leftovers freeze well.'),
  R('d-salmon', 'Baked salmon, quinoa & green beans', 'dinner', 520, 39, 38, 25, 'salmon:.33 quinoa:.1 gbeans:.25 lemon:.25 oil:.5', 'Cook quinoa.|Bake salmon and green beans with oil, salt and lemon slices at 400°F for 12–15 minutes.|Serve over quinoa.'),
  R('d-stirfry', 'Tofu veggie stir-fry', 'dinner', 480, 22, 60, 25, 'tofu:5 rice:.1 broc:.2 pepper:.3 carrot:.1 soy:1 ginger:.5 garlic:1 sesoil:.5', 'Cook rice.|Press and cube tofu; brown in sesame oil for 8 minutes.|Add vegetables, garlic and ginger; stir-fry 5 minutes and finish with soy sauce.'),
  R('d-lentilcurry', 'Lentil & sweet potato curry', 'dinner', 520, 18, 75, 40, 'lentils:.12 swpot:.3 coco:.2 tomcan:.25 spinach:1 curry:1 onion:.2 rice:.08', 'Cook rice.|Sauté onion with curry paste for 3 minutes.|Add lentils, cubed sweet potato, tomatoes, coconut milk and ½ cup water per serving; simmer 25 minutes.|Stir in spinach.'),
  R('d-meatballs', 'Turkey meatballs with pasta', 'dinner', 520, 36, 60, 35, 'turkey:.25 pasta:.12 tomcan:.3 zucc:.2 parm:.25 garlic:1 eggs:.25', 'Mix turkey, egg, garlic and half the parmesan; roll into balls.|Brown meatballs, add tomatoes and diced zucchini, simmer 15 minutes.|Serve over pasta with the remaining parmesan.'),
  R('d-beantacos', 'Black bean tacos with slaw', 'dinner', 420, 15, 65, 20, 'blackb:.4 corntort:3 cabbage:.1 avo:.25 salsa:.15 lime:.25 spice:.5', 'Warm beans with spice blend, mashing slightly.|Toss shredded cabbage with lime juice.|Fill warm tortillas with beans, slaw, avocado and salsa.'),
  R('d-fajitas', 'Shrimp fajitas', 'dinner', 380, 28, 40, 20, 'shrimp:.25 pepper:.5 onion:.25 corntort:3 lime:.25 spice:.5 oil:.5', 'Slice peppers and onion; sear in oil for 6 minutes.|Add shrimp and spice blend; cook 3 minutes until pink.|Serve in tortillas with lime.'),
  R('d-lemonchix', 'Lemon garlic chicken thighs & potatoes', 'dinner', 520, 36, 35, 45, 'thigh:.35 potato:.3 gbeans:.2 lemon:.25 oil:.75 garlic:1', 'Heat oven to 425°F.|Toss potatoes with oil; roast 15 minutes.|Add chicken, green beans, garlic and lemon; roast 25 minutes more.'),
  R('d-beefbroc', 'Beef & broccoli over cauliflower rice', 'dinner', 400, 30, 15, 20, 'beef:.25 broc:.3 caulirice:4 soy:1 garlic:1 ginger:.5 sesoil:.5', 'Brown beef with garlic and ginger.|Add broccoli and a splash of water; cover for 4 minutes.|Stir in soy sauce and sesame oil; serve over warmed cauliflower rice.'),
  R('d-peppers', 'Turkey stuffed peppers', 'dinner', 430, 30, 35, 45, 'turkey:.2 pepper:1 rice:.06 tomcan:.25 mozz:.5 onion:.15 spice:.5', 'Cook rice and heat oven to 375°F.|Brown turkey with onion and spices; mix with rice and tomatoes.|Fill halved peppers, top with mozzarella and bake 25 minutes.'),
  R('d-chickcurry', 'Chickpea spinach coconut curry', 'dinner', 510, 15, 65, 30, 'chick:.5 coco:.2 tomcan:.25 spinach:1.5 curry:1 onion:.2 rice:.08', 'Cook rice.|Sauté onion with curry paste.|Add chickpeas, tomatoes and coconut milk; simmer 15 minutes and stir in spinach.'),
  R('d-cod', 'Baked cod with sweet potato & broccoli', 'dinner', 380, 32, 38, 30, 'cod:.33 swpot:.3 broc:.25 lemon:.25 oil:.75', 'Heat oven to 425°F and roast cubed sweet potato 15 minutes.|Add broccoli and cod brushed with oil and lemon; roast 12 minutes more.'),
  R('d-primavera', 'Whole-wheat pasta primavera', 'dinner', 500, 20, 78, 25, 'pasta:.15 zucc:.2 pepper:.3 peas:2 parm:.5 oil:.75 garlic:1', 'Boil pasta, adding peas for the last 2 minutes.|Sauté zucchini, pepper and garlic in oil.|Toss with drained pasta and parmesan.'),
  R('d-friedrice', 'Veggie egg fried rice', 'dinner', 420, 17, 55, 20, 'eggs:2 rice:.1 mixveg:3 soy:1 scal:.1 sesoil:.5', 'Cook rice ahead (day-old is best).|Scramble eggs in sesame oil and set aside.|Stir-fry vegetables and rice; add eggs, soy sauce and green onions.'),
  R('d-zoodle', 'Turkey bolognese with zucchini noodles', 'dinner', 350, 33, 18, 30, 'turkey:.25 zucc:.4 tomcan:.35 onion:.15 garlic:1 parm:.25', 'Brown turkey with onion and garlic.|Add tomatoes and simmer 15 minutes.|Spiralize or thinly slice zucchini, sauté 2 minutes, then top with sauce and parmesan.'),
  R('d-shepherd', "Lentil shepherd's pie", 'dinner', 430, 18, 75, 50, 'lentils:.12 potato:.35 carrot:.15 peas:2 onion:.2 vbroth:.5 oil:.5', 'Boil potatoes and mash with oil and salt.|Simmer lentils, carrot, onion and broth for 25 minutes; stir in peas.|Top with the mash and bake at 400°F for 15 minutes.'),
  R('d-chixsoup', 'Chicken vegetable rice soup', 'dinner', 330, 30, 30, 40, 'chix:.25 carrot:.15 onion:.25 rice:.05 cbroth:2 zucc:.15', 'Simmer broth, rice, diced onion and carrot for 20 minutes.|Add diced chicken and zucchini; simmer 10 minutes more.'),
  R('d-quesadilla', 'Bean & veggie quesadillas', 'dinner', 480, 20, 55, 15, 'wwtort:2 blackb:.25 cheddar:1 pepper:.25 spinach:.5 salsa:.1', 'Fill tortillas with beans, cheese, diced pepper and spinach.|Cook in a dry pan 3 minutes per side.|Cut into wedges and serve with salsa.'),
  R('d-turkeyburger', 'Turkey burgers & sweet potato wedges', 'dinner', 420, 30, 35, 35, 'turkey:.25 swpot:.3 romaine:.2 tomato:.5 onion:.1 oil:.5', 'Roast oiled sweet potato wedges at 425°F for 25 minutes.|Shape turkey into patties and cook 5 minutes per side.|Serve in lettuce wraps with tomato and onion.'),
  R('d-salmoncauli', 'Salmon with roasted broccoli & cauliflower', 'dinner', 450, 38, 15, 30, 'salmon:.33 broc:.25 cauli:.25 oil:.75 lemon:.25', 'Heat oven to 425°F; roast broccoli and cauliflower florets with oil for 15 minutes.|Add salmon with lemon; roast 12 minutes more.'),
  R('d-caulifried', 'Chicken cauliflower fried rice', 'dinner', 380, 36, 18, 20, 'chix:.25 caulirice:5 mixveg:2 eggs:1 soy:1 scal:.1 sesoil:.5', 'Dice chicken and cook in sesame oil for 6 minutes.|Add cauliflower rice and vegetables; stir-fry 5 minutes.|Push aside, scramble the egg, then toss everything with soy sauce and green onions.'),
];
